export * from './usuario.reducer';
export * from './AUDGENPROCESO.reducer';
export * from './listaUsuarios.reducer';
export * from './loaderProcesoCambios.reducer';
export * from './AUDGENESTADOPROCESO.reducer';
export * from './AUDGENEJECUCIONESPROCESO.reducer';
export * from './CATPROCESO.reducer';
export * from './CATPERMISOS.reducer';
export * from './notificaciones.reducer'
export * from './catalogos/catalogos.reducer'
