export interface NOTIFICACION_INTERFACE {
  __typename: string;
  ESTADO_EJECUCION: string;
  ETAPA_INICIAL_ESTADO_INICIAL: string;
  ETAPA_INICIAL_ESTADO_FINAL: string;
  ETAPA_INICIAL_FECHA_INICIAL: string;
  ETAPA_INICIAL_FECHA_FINAL: string;
  ETAPA_FINAL_ESTADO_INICIAL: string;
  ETAPA_FINAL_ESTADO_FINAL: string;
  ETAPA_FINAL_FECHA_INICIAL: string;
  ETAPA_FINAL_FECHA_FINAL: string;
  ETAPA_PROCESAMIENTO_ESTADO_INICIAL: string;
  ETAPA_PROCESAMIENTO_ESTADO_FINAL: string;
  ETAPA_PROCESAMIENTO_FECHA_INICIAL: string;
  ETAPA_PROCESAMIENTO_FECHA_FINAL: string;
  FECHA_ACTUALIZACION: string;
  FECHA_CREADO: string;
  FECHA_FINALIZADO: string;
  INSUMO: string;
  INTERFAZ: string;
  TIPO_PROCESO: string;
  LEIDO: boolean;




}
