/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Ftm7m3Om2",
    "aws_user_pools_web_client_id": "5cvq4jop6octili7583n597kd1",
    "oauth": {
        "domain": "sia-app-up.auth.us-east-1.amazoncognito.com"
    },
    "aws_appsync_graphqlEndpoint": "https://z3z4liprmfgfjl4twtn24dambm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
